baseURL: "https://lostsquirrel.github.io/k8sDocs"
languageCode: "zh-cn"
title: "K8S 文档笔记"
defaultContentLanguage: "zh"
theme: techdoc
hascjklanguage: true
metaDataFormat: yaml
params:
  description: test
  title: "K8S 文档笔记"
  menu_style: slide-menu
  baidu_tongji_id: 46e26ffc9d975f663dff0b89f1cf7931
  github_doc_repository: https://github.com/lostsquirrel/k8sDocs
  language_alternatives:
    - en
  showedit: true
  latest: "v1.18"
  fullversion: "v1.18.0"
  version: "v1.18"
  githubbranch: "master"
  docsbranch: "master"
languages:
  zh:
    title: "Kubernetes"
    description: "生产级别的容器编排系统"
    languageName: "中文 Chinese"
    weight: 2
    contentDir: "content/zh"
    languagedirection: "ltr"
markup:
  goldmark:
    renderer:
      unsafe: true


announcement: true
custom:
  baseImageURL: https://d33wubrfki0l68.cloudfront.net/aecab1f649bc640ebef1f05581bfcc91a48038c4/728d6/images/docs/pod.svg
